# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cef74d90a0ace49686ce102a06cf14c56f32dc5b91b266645f57438260733f91985ffc75f8aa32aaed905b8b29edae4229f54f852a2a759fbe2847be1f9164c

test:
  secret_key_base: a145d5cd75ae686eedb66b952066071365acbda0ecccd7b20db0170975375e371b90a946b6e91453184a43c42fad5abef796727676637d432c9f58a3e61bf961

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
